
// def_names for all the name objects that are used

// Mouse :
def_name ( LButtonDblclk )	// left mouse button double clicked
def_name ( LButtonDown )	// left mouse button down/pressed
def_name ( LButtonUp )		// left mouse button up/released
def_name ( MButtonDown )	// middle mouse button down/pressed
def_name ( MButtonUp )		// middle mouse button up/released
def_name ( mouseScroll )	// mouse middle button is scrolled
def_name ( mouseMoved )		// mouse is moved
def_name ( rButtonDown )	// right mouse button down/pressed
def_name ( rButtonUp )		// right mouse button up/released

// View related:
def_name ( redrawView )
def_name ( nodeClicked )
def_name ( connectionChanged )
def_name ( zoom )
def_name ( pan )
def_name ( redrawNode )
def_name ( findNodeByPos )
def_name ( getNodeCount )
def_name ( nodesDeleted )
def_name ( allowUIDelete )
def_name ( selectedNodeIndex )
def_name ( backgroundBitmap )
def_name ( backgroundPath )
def_name ( allowZoom )
def_name ( allowPan )
def_name ( regionSelected )
def_name ( tileBackground )
def_name ( keyboardDown )
def_name ( keyboardUp )
def_name ( showInfo )
def_name ( drawWeights )
def_name ( allowRegionSelect )
def_name ( getDeletedNodeCount )
def_name ( getDeletedNodeIndex )
def_name ( setRenderBall )
def_name ( preNodesDeleted )
def_name ( connectToEmpty )
def_name ( connectionStarted )
def_name ( drawShadows )
def_name ( drawLastIndex )
def_name ( drawMenuBars )
def_name ( zoomAboutMouse )
def_name ( nodeTransparency )
def_name ( setInfo )
def_name ( useDrawLayers )

// Node related :
def_name ( addNode )
def_name ( activeNode )
def_name ( deleteActiveNode )
def_name ( getSelectionCount )
def_name ( nodeName )
def_name ( nodeBitmap )
def_name ( activeNodePos )
def_name ( activeNodePosRelative )
def_name ( activeNodeCollapsed )
def_name ( nodeColor )
def_name ( nodeSize )
def_name ( isHidden )
def_name ( bitmapPath )
def_name ( sceneNode )
def_name ( nodeInfo )
def_name ( posLocked )
def_name ( nodeNameOffset )
def_name ( selectable )
def_name ( isselected )
def_name ( nodeCollapsedSize )
def_name ( edgeSize )
def_name ( showBitmapOnly )
def_name ( isCollapsible )
def_name ( parentNode )
def_name ( getChildCount )
def_name ( childIndex )
def_name ( drawConnectionsFromParent )
def_name ( getSelectedConnectionNodeAndSocket )
def_name ( textAlign )
def_name ( bitmapSize )
def_name ( viewAlign )
def_name ( viewAlignOffset )
def_name ( showMiniBitmap )
def_name ( drawLayer )

// Socket related:
def_name ( addInSocket )
def_name ( addOutSocket )
def_name ( activeSocket )
def_name ( deleteActiveSocket )
def_name ( getSocketCount )
def_name ( socketName )
def_name ( toggleConnection )
def_name ( activeSocketFlipped )
def_name ( activeSocketValue )
def_name ( activeSocketShowValue )
def_name ( getActiveSocketType )
def_name ( getActiveSocketConnectingNodeIndices )
def_name ( getActiveSocketConnectingSocketIndices )
def_name ( sceneController )
def_name ( socketPosition )
def_name ( connectionColor )
def_name ( socketLabelOffset )
def_name ( socketDataClass )
def_name ( socketValueChanged )
def_name ( connectionSelectionChanged )
def_name ( getSelectedConnectionIndex )
def_name ( socketInfo )
def_name ( setConnectionWeight )
def_name ( getConnectionWeight )
def_name ( socketIsHidden )
def_name ( drawSeperator )

